/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'catalogNumber' : IDL.Text,
  'grade' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'applications' : IDL.Vec(IDL.Text),
  'packSizes' : IDL.Vec(IDL.Text),
});
export const ContactDetails = IDL.Record({
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CompanyInfo = IDL.Record({
  'name' : IDL.Text,
  'partners' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'contactDetails' : ContactDetails,
});
export const QuoteRequest = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'catalogNumber' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Text,
  'phone' : IDL.Text,
  'casNumber' : IDL.Text,
});
export const QuoteRequestInput = IDL.Record({
  'customerName' : IDL.Text,
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'catalogNumber' : IDL.Text,
  'message' : IDL.Text,
  'quantity' : IDL.Text,
  'phone' : IDL.Text,
  'casNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterProducts' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'filterProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'getPaginatedProducts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
  'getQuoteRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitQuoteRequest' : IDL.Func([QuoteRequestInput], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'catalogNumber' : IDL.Text,
    'grade' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'applications' : IDL.Vec(IDL.Text),
    'packSizes' : IDL.Vec(IDL.Text),
  });
  const ContactDetails = IDL.Record({
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CompanyInfo = IDL.Record({
    'name' : IDL.Text,
    'partners' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'contactDetails' : ContactDetails,
  });
  const QuoteRequest = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'catalogNumber' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Text,
    'phone' : IDL.Text,
    'casNumber' : IDL.Text,
  });
  const QuoteRequestInput = IDL.Record({
    'customerName' : IDL.Text,
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'catalogNumber' : IDL.Text,
    'message' : IDL.Text,
    'quantity' : IDL.Text,
    'phone' : IDL.Text,
    'casNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'filterProducts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'getPaginatedProducts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
    'getQuoteRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'submitQuoteRequest' : IDL.Func([QuoteRequestInput], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };