/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyInfo {
  'name' : string,
  'partners' : Array<string>,
  'address' : string,
  'contactDetails' : ContactDetails,
}
export interface ContactDetails {
  'email' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'catalogNumber' : string,
  'grade' : string,
  'category' : string,
  'brand' : string,
  'applications' : Array<string>,
  'packSizes' : Array<string>,
}
export interface QuoteRequest {
  'id' : string,
  'customerName' : string,
  'productName' : string,
  'email' : string,
  'catalogNumber' : string,
  'message' : string,
  'timestamp' : bigint,
  'quantity' : string,
  'phone' : string,
  'casNumber' : string,
}
export interface QuoteRequestInput {
  'customerName' : string,
  'productName' : string,
  'email' : string,
  'catalogNumber' : string,
  'message' : string,
  'quantity' : string,
  'phone' : string,
  'casNumber' : string,
}
export interface _SERVICE {
  'filterProducts' : ActorMethod<[string, string], Array<Product>>,
  'filterProductsByBrand' : ActorMethod<[string], Array<Product>>,
  'filterProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCompanyInfo' : ActorMethod<[], CompanyInfo>,
  'getPaginatedProducts' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProductById' : ActorMethod<[string], Product>,
  'getQuoteRequestCount' : ActorMethod<[], bigint>,
  'getQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'submitQuoteRequest' : ActorMethod<[QuoteRequestInput], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];